add home page and about page for desktop and mobile user
milen-ale/Capstone pull request #1
Opened 2022-07-01 22:53 UTC by milen-ale

In this capstone project, I build a website for Microverse by following the design guidelines including Color, Typograpghy, and Layout from the original design on Behance by Cindy Shin. During this project, I designed two different pages

Home Page
About Page
I designed these two pages for both mobile and desktop users.

2022-07-01 23:41 UTC, uwadonat requested changes
## Hi @milen-ale, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Your design looks nice ✔️
- No linter errors ✔️
- You are correctly using github flow ✔️

## Required Changes ♻️
_Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 23:41 UTC, uwadonat commented on README.md
> +# capestone-project-
- [ ]  Please update your readme file. You can follow Microverse [template](https://github.com/microverseinc/readme-template/blob/master/README.md).

- [ ] Kindly add link for a loom video showing project in desktop and mobile version. Again highlight peace of code you are proud of.
- [ ] You should use of GitHub Pages to deploy the web pages and add link in your readme file.

2022-07-01 23:41 UTC, uwadonat commented on index.html
> +
- [ ] Make sure all images contain alt attributes. Example: `alt="my-image"`

2022-07-01 23:41 UTC, uwadonat commented on index.html
> +        <div>
- [ ] Please remove all commented lines to make your project more clean

2022-07-02 10:42 UTC, medaminedev66 requested changes
Hi @milen-ale 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
-  The video presentation was really good.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 10:42 UTC, medaminedev66 commented on README.md
> +You can checkout the live version [here](https://milen-ale.github.io/capstone/)
- [ ] The live demo link is broken. Kindly fix this so that your project is complete.

2022-07-02 11:15 UTC, Rustamxon7 approved these changes
## Hi team 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-02 14:49 UTC, merged